config/routes.rb
Rails.application.routes.draw do
  resources :labels
  resources :tasks
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  get 'pages/home'
  get 'pages/dashboard'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/label.rb
class Label
  include Mongoid::Document
  field :name, type: String
end

app/models/task.rb
class Task
  include Mongoid::Document
  field :title, type: String
  field :status, type: String, default: 'backlog'
  field :description, type: String
  field :due_date, type: Date
  embedded_in :user

  validates_presence_of :title, :description
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  embeds_many :tasks

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  # field :sign_in_count,      type: Integer, default: 0
  # field :current_sign_in_at, type: Time
  # field :last_sign_in_at,    type: Time
  # field :current_sign_in_ip, type: String
  # field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def after_sign_in_path_for(resource)
		stored_location_for(resource) || pages_dashboard_path
	end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: [:show, :edit, :update, :destroy]

  # GET /labels
  # GET /labels.json
  def index
    @labels = Label.all
  end

  # GET /labels/1
  # GET /labels/1.json
  def show
  end

  # GET /labels/new
  def new
    @label = Label.new
  end

  # GET /labels/1/edit
  def edit
  end

  # POST /labels
  # POST /labels.json
  def create
    @label = Label.new(label_params)

    respond_to do |format|
      if @label.save
        @task.update_attribute(label: @label.name)
        format.html { redirect_to @label, notice: 'Label was successfully created.' }
        format.json { render :show, status: :created, location: @label }
      else
        format.html { render :new }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labels/1
  # PATCH/PUT /labels/1.json
  def update
    respond_to do |format|
      if @label.update(label_params)
        format.html { redirect_to @label, notice: 'Label was successfully updated.' }
        format.json { render :show, status: :ok, location: @label }
      else
        format.html { render :edit }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labels/1
  # DELETE /labels/1.json
  def destroy
    @label.destroy
    respond_to do |format|
      format.html { redirect_to labels_url, notice: 'Label was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_label
      @label = Label.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def label_params
      @task = current_user.tasks.where(id: params[:label][:task_id])

      params.require(:label).permit(:name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :authenticate_user!, only: :dashboard

	def home
	end

	def dashboard
		@task = Task.new
		@tasks = current_user.tasks
		@label = Label.new
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = current_user.tasks
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = current_user.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.js
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.js
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.js
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.js
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = current_user.tasks.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :due_date, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/labels/_form.html.erb
<div class="modal-content">
  <%= form_for label, remote: true do |form| %>
  <% if label.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(label.errors.count, "error") %> prohibited this label from being saved:</h2>

    <ul>
      <% label.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Add Label</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <div class="field">
      <%= form.label :name %><br>
      <%= form.text_field :name %>
      <%= form.hidden_field :task_id, value: task_id %>
    </div>

  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <button type="button" class="btn btn-primary">Save</button>
  </div>

  <% end %>
</div>

app/views/labels/edit.html.erb
<h1>Editing Label</h1>

<%= render 'form', label: @label %>

<%= link_to 'Show', @label %> |
<%= link_to 'Back', labels_path %>

app/views/labels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Labels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @labels.each do |label| %>
      <tr>
        <td><%= label.name %></td>
        <td><%= link_to 'Show', label %></td>
        <td><%= link_to 'Edit', edit_label_path(label) %></td>
        <td><%= link_to 'Destroy', label, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Label', new_label_path %>

app/views/labels/new.html.erb
<h1>New Label</h1>

<%= render 'form', label: @label %>

<%= link_to 'Back', labels_path %>

app/views/labels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @label.name %>
</p>

<%= link_to 'Edit', edit_label_path(@label) %> |
<%= link_to 'Back', labels_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<nav class="navbar navbar-default">
		<div class="container-fluid">

			<ul class='nav navbar-nav'>
				<h2>
					<a href="/"> TASk APP </a>
			</h2>
			</ul>

	</nav>

			<ul class="nav navbar-nav navbar-right">
				<% if current_user %>
					 <%= link_to current_user.email, user_session_path(current_user) %> &nbsp;
					 <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
				<% else %>
					<%= link_to 'Login', new_user_session_path %> &nbsp;
					<%= link_to 'Register', new_user_registration_path %>
				<% end %>
			</ul>

			</div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'layouts/header' %>
  
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <%= yield %>
      </div>
    </div>
    <footer>
      <p>&copy; Company 2019</p>
    </footer>
    
  </div>

</body>
</html>

app/views/pages/dashboard.html.erb
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">

<p id="notice"><%= notice %></p>

<h1>Dashboards</h1>

<div class="actions">
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#taskModal">
  Add Task</button>

  <!-- Modal -->
  <div class="modal fade" data-backdrop="static" id="taskModal" tabindex="-1" role="dialog" aria-labelledby="taskModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <%= render 'tasks/form', task: @task%>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-md-3 border shadow">
        <h2 class='border-bottom'>Backlog</h2>
        <div class="droppable" id='backlog'>

          <% @tasks.where(status: 'backlog').each do |task|%>
            <%= render 'tasks/task', task: task %>
          <% end %>

        </div>
      </div>

      <div class="col-md-3 border shadow">
        <h2 class='border-bottom'>Inprogress</h2>
        <div class="droppable" id='inprogress'>
          
          <% @tasks.where(status: 'inprogress').each do |task|%>
            <%= render 'tasks/task', task: task %>
          <% end %>
          
        </div>
      </div>

      <div class="col-md-3 border shadow">
        <h2 class='border-bottom'>Under Review</h2>
        <div class="droppable" id='underReview'>
          
          <% @tasks.where(status: 'underReview').each do |task|%>
            <%= render 'tasks/task', task: task %>
          <% end %>
          
        </div>
      </div>

      <div class="col-md-3 border shadow">
        <h2 class='border-bottom'>Complete</h2>
        <div class="droppable" id='complete'>
          
          <% @tasks.where(status: 'complete').each do |task|%>
            <%= render 'tasks/task', task: task %>
          <% end %>
          
        </div>
      </div>

    </div>

  </div>

</div>

app/views/pages/home.html.erb
<h1>Home Page</h1>
<h2>Welcome to Home Page.....</h2>
<p>Our online dashboard creator enables you to see more than just facts and figures. Our tool connects to all common data sources such as databases, flat files...to turn your raw data into something far more understandable for yourself and your colleagues.Additionally, our easy to access templates, which you can choose right after your login, provides an added feature for users who don’t want to build their own dashboards.</p>

app/views/tasks/_form.html.erb
<div class="modal-content">
  <%= form_for task, remote: true do |form| %>
  <% if task.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

    <ul>
      <% task.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Add a Task</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-text' %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description, class: 'form-text' %>
    </div>

    <div class="field">
      <%= form.label :due_date %>
      <%= form.date_field :due_date, class: 'form-text' %>
    </div>

  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
    <%= form.submit 'Save',class: 'btn btn-primary' %>
  </div>
  
  <% end %>

</div>

app/views/tasks/_task.html.erb
<div class="card draggable" data-task-id="<%= task.id %>">
	
	<div class="card-body">
		<h5 class="card-title"><%= task.title %></h5>
		<h6 class="card-subtitle mb-2 text-muted">due: <%= task.due_date %></h6>
		<p class="card-text"><%= task.description %></p>
		<div class="btn-group">
			<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#labelModal">Add Label</button>
			<button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				<span class="sr-only">Toggle Dropdown</span>
			</button>
		</div>
	</div>

</div>
<!-- Modal -->
<div class="modal fade" id="labelModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<%= render 'labels/form', label: @label, task_id: @task.id %>
	</div>
</div>

app/views/tasks/create.js.erb
<%- if @task.errors.blank? -%>
  $('#backlog').append("<%= escape_javascript(render 'tasks/task', task: @task) %>")
  $('#taskModal').modal('hide')
  $(".draggable").draggable({});

<%- else -%>
  alert('inside create.js.erb: failed')
<%- end -%>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Due date</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.due_date %></td>
        <td><%= task.user %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @task.due_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @task.user %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>